import Head from 'next/head'

export default function Title() {
    return (
        <Head>
            <title>News App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/image/logo.svg" />
        </Head>
    )
}